print('Mohammad Hossein Movahedi')
print('Module 2 Technique Practice')

#libraries added
install.packages('FSA')
install.packages('magrittr')
install.packages('dplyr')
install.packages('tidyr')
install.packages('plyr')
install.packages('tidyverse')
install.packages('outliers')
install.packages('ggplot2')
install.packages('lubridate')
install.packages("janitor")
install.packages('imputeTS')
install.packages('corrplot')
install.packages('mctest')
install.packages('leaps')

library(FSA)
library(magrittr)
library(dplyr)
library(tidyr)
library(plyr)
library(tidyverse)
library(scales)
library(lubridate)
library(ggplot2)
library(outliers)
library(janitor)
library(corrplot)

library(leaps)